: ${SMARTTHINGS_BRIDGE_LOCAL_ADDRESS:=localhost}
: ${SMARTTHINGS_BRIDGE_LOCAL_PORT:=5566}
: ${SMARTTHINGS_BRIDGE_GLOBAL_ADDRESS:=localhost}
: ${SMARTTHINGS_BRIDGE_GLOBAL_PORT:=5566}
: ${SMARTTHINGS_TARGET_CONFIG:=`rospack find rocon_smartthings_bridge`/resources/default.json}

export SMARTTHINGS_BRIDGE_LOCAL_ADDRESS
export SMARTTHINGS_BRIDGE_LOCAL_PORT
export SMARTTHINGS_BRIDGE_GLOBAL_ADDRESS
export SMARTTHINGS_BRIDGE_GLOBAL_PORT
export SMARTTHINGS_TARGET_CONFIG
