
: ${NINJABLOCK_BRIDGE_LOCAL_ADDRESS:=localhost}
: ${NINJABLOCK_BRIDGE_LOCAL_PORT:=5555}
: ${NINJABLOCK_BRIDGE_GLOBAL_ADDRESS:=localhost}
: ${NINJABLOCK_BRIDGE_GLOBAL_PORT:=5555}
: ${NINJABLOCK_TARGET_CONFIG:=`rospack find rocon_ninjablock_bridge`/resources/default.json}

export NINJABLOCK_BRIDGE_LOCAL_ADDRESS
export NINJABLOCK_BRIDGE_LOCAL_PORT
export NINJABLOCK_BRIDGE_GLOBAL_ADDRESS
export NINJABLOCK_BRIDGE_GLOBAL_PORT
export NINJABLOCK_TARGET_CONFIG
